PGM

  /* Step 1: Delete and recreate PLACEMENT file                        */
  DLTF FILE(AXAINS/PLACEMENT)
  MONMSG MSGID(CPF2105) EXEC(GOTO CMDLBL(SKIP1))
  CRTPF FILE(AXAINS/PLACEMENT) RCDLEN(83)
  SKIP1:

ENDPGM
