PGM

  /* Step 1: Delete and recreate SUBMISSION file                       */
  DLTF FILE(AXAINS/SUBMISSION)
  MONMSG MSGID(CPF2105) EXEC(GOTO CMDLBL(SKIP1))
  CRTPF FILE(AXAINS/SUBMISSION) RCDLEN(70)
  SKIP1:

ENDPGM
